name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec middleman build

    - uses: DFE-Digital/github-actions/setup-cf-cli@master
      name: Install cf CLI
      with:
        CF_USERNAME: ${{ secrets.CF_USER }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_SPACE_NAME: bat-qa

    - run: cf push bat-tech-guide
